name: Build Documentation

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./docs~/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: ./docs~/pnpm-lock.yaml
      - run: pnpm install
        working-directory: ./docs~
      - run: pnpm run build
        working-directory: ./docs~