name: Build Documentation

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  DOCFX_PROJECT_PATH: .docfx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"
      - name: Install DocFX
        run: dotnet tool update -g docfx
      - name: Clean DocFX output
        run: rm -rf "$DOCFX_PROJECT_PATH/_site"
      - name: Build documentation
        run: docfx ${{ env.DOCFX_PROJECT_PATH }}/docfx.json
